# 3D Drone Training Curriculum
# Progressive difficulty system for ML-Agents training

behaviors:
  DroneAgent:
    trainer_type: ppo
    
    # Core hyperparameters
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005           # Entropy bonus (exploration)
      epsilon: 0.2          # PPO clipping
      lambd: 0.95          # GAE lambda
      num_epoch: 3
      learning_rate_schedule: linear  # Decay over time
    
    # Neural network architecture
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    
    # Reward signals
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      
      # Curiosity module (helps exploration)
      curiosity:
        gamma: 0.99
        strength: 0.01
        encoding_size: 256
    
    # Training settings
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000
    
    # Self-play (not used for single drone)
    self_play: null
    behavioral_cloning: null

# ==============================================================================
# CURRICULUM: Progressive Training Stages
# ==============================================================================

environment_parameters:
  target_distance:
    curriculum:
      - name: hover_training
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 5.0
        value: 0.0
      
      - name: close_target
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 10.0
        value: 5.0
      
      - name: medium_target
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 15.0
        value: 10.0
      
      - name: static_obstacles
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 12.0
        value: 10.0
      
      - name: complex_obstacles
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 12.0
        value: 15.0
      
      - name: wind_challenge
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 10.0
        value: 15.0
      
      - name: long_distance
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 15.0
        value: 25.0
      
      - name: expert_flight
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 20.0
        value: 30.0
  
  obstacle_count:
    curriculum:
      - name: hover_training
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 5.0
        value: 0
      
      - name: close_target
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 10.0
        value: 0
      
      - name: medium_target
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 15.0
        value: 0
      
      - name: static_obstacles
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 12.0
        value: 3
      
      - name: complex_obstacles
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 12.0
        value: 6
      
      - name: wind_challenge
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 10.0
        value: 6
      
      - name: long_distance
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 15.0
        value: 8
      
      - name: expert_flight
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 20.0
        value: 10
  
  wind_strength:
    curriculum:
      - name: hover_training
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 5.0
        value: 0.0
      
      - name: close_target
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 10.0
        value: 0.0
      
      - name: medium_target
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 15.0
        value: 0.0
      
      - name: static_obstacles
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 12.0
        value: 0.0
      
      - name: complex_obstacles
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 12.0
        value: 0.0
      
      - name: wind_challenge
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 10.0
        value: 2.0
      
      - name: long_distance
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 15.0
        value: 3.0
      
      - name: expert_flight
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 20.0
        value: 5.0
